### PR TITLE
Packer release updates

### PR DESCRIPTION
**Pull request by btassone**
Continuing discussion here

### CODE REVIEW

**Comment by btassone** [comment]
Ignore the extraneous .goreleaser.yml file changed. Wanted a PR that was open more relevant to the renaming change so just did this quickly. Let me know if the build output is what you all want please :)

Sorry for the delay, been a very busy past 2 weeks.

**Comment by btassone** [comment]
[packer-plugin-goss-v3.2.1-pre](https://github.com/YaleUniversity/packer-plugin-goss/releases/tag/v3.2.1-pre)

Contains the build assets with the new project name change, aside from the -pre (which is dropped for latest releases). Is this correct?

**Comment by FalcoSuessgott** [comment]
i can verify it works !!! :) 

```hcl
packer {
  required_version = ">= 1.9.0"

  required_plugins {
    openstack = {
      version = "1.1.1"
      source  = "github.com/hashicorp/openstack"
    }
    goss = {
      version = "3.2.1-pre"
      source = "github.com/YaleUniversity/goss"
    }
  }
}
```

```bash
packer init .
Installed plugin github.com/yaleuniversity/goss v3.2.1-pre in "/home/morelly_t1/git/sva/cc-in-au/solutions/golden-image-factory/_plugins/github.com/yaleuniversity/goss/packer-plugin-goss_v3.2.1-pre_x5.0_linux_amd64"
```

**Comment by FalcoSuessgott** [comment]
Thanks a lot @btassone for your help and patience. Maybe release an official tag and then we can finally relax :D

**Comment by btassone** [comment]
> Thanks a lot @btassone for your help and patience. Maybe release an official tag and then we can finally relax :D

Haha roger that. Not a problem. Thank you all for your patience! I'll cut it right now

**Pull request merged**
